language: node_js
node_js:
  - "6"
before_script:
  - npm rebuild phantomjs-prebuilt
  - node node_modules/optipng-bin/lib/install.js
  - node node_modules/pngquant-bin/lib/install.js
  - node node_modules/gifsicle/lib/install.js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - pngquant
script:
- npm rebuild node-sass
- npm run build