language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - npm rebuild phantomjs-prebuilt
env:
  - CXX=g++-4.8
script:
  - npm rebuild node-sass
  - npm run build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
